import { Category } from "@lib/types/category";
import { Customer, OrderStatus } from "@lib/types/customer";
import { CurrencyCode, Product, SizeNames } from "@lib/types/product";

export const categories: Category[] = [
  {
    id: "cat-1",
    name: "Plates",
    url: "/search?category=plates",
    image: "https://picsum.photos/600/600?random=201",
    slug: "plates",
  },
  {
    id: "cat-2",
    name: "Mugs",
    url: "/search?category=mugs",
    image: "https://picsum.photos/600/600?random=202",
    slug: "mugs",
  },
  {
    id: "cat-3",
    name: "Vases",
    url: "/search?category=vases",
    image: "https://picsum.photos/600/600?random=203",
    slug: "vases",
  },
  {
    id: "cat-4",
    name: "Bowls",
    url: "/search?category=bowls",
    image: "https://picsum.photos/600/600?random=204",
    slug: "bowls",
  },
  {
    id: "cat-5",
    name: "Cups",
    url: "/search?category=cups",
    image: "https://picsum.photos/600/600?random=205",
    slug: "cups",
  },
  {
    id: "cat-6",
    name: "Planters",
    url: "/search?category=planters",
    image: "https://picsum.photos/600/600?random=206",
    slug: "planters",
  },
  {
    id: "cat-7",
    name: "Boxes",
    url: "/search?category=boxes",
    image: "https://picsum.photos/600/600?random=207",
    slug: "boxes",
  },
];

export const products: Product[] = [
  // --- Product 1: Multiple Variants (Size & Color) ---
  {
    id: "p1",
    name: "Minimalist Ceramic Vase",
    description: "A hand-thrown stoneware vase with a matte finish.",
    slug: "minimalist-ceramic-vase",
    images: ["https://picsum.photos/seed/vase1/600/600"],
    categories: ["vases"],
    requiresShipping: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    variants: [
      {
        id: "v1",
        sku: "VASE-S-WHT",
        price: 35.0,
        currency: CurrencyCode.GBP, // Matches your type "typeof CurrencyCode"
        stock: 12,
        availableForSale: true,
        sizeName: SizeNames.S,
        widthCm: 10,
        heightCm: 15,

        colorName: "Studio White",
        colorHex: "#FFFFFF",
        productId: "p1",
        createdAt: new Date(),
        updatedAt: new Date(),
        depthCm: 0,
        images: [
          "https://picsum.photos/seed/vase11/600/600",
          "https://picsum.photos/seed/vase11/600/600",
          "https://picsum.photos/seed/vase13/600/600",
          "https://picsum.photos/seed/vase12/600/600",
        ],
      },
      {
        id: "v2",
        sku: "VASE-M-WHT",
        price: 45.0,
        currency: CurrencyCode.GBP,
        stock: 8,
        availableForSale: true,
        sizeName: SizeNames.M,
        widthCm: 15,
        heightCm: 22,
        colorName: "Studio White",
        colorHex: "#FFFFFF",
        productId: "p1",
        createdAt: new Date(),
        updatedAt: new Date(),
        images: ["https://picsum.photos/seed/vasew/600/600"],
        depthCm: 10,
      },
    ],
  },

  // --- Product 2: Multiple Variants (Colors) ---
  {
    id: "p2",
    name: "Artisan Coffee Mug",
    description: "The perfect weight and grip for your morning brew.",
    slug: "artisan-coffee-mug",
    images: ["https://picsum.photos/seed/mug1/600/600"],
    categories: ["Kitchen", "Ceramics"],
    requiresShipping: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    variants: [
      {
        id: "v3",
        sku: "MUG-BLU",
        price: 22.0,
        currency: CurrencyCode.GBP,
        stock: 50,
        availableForSale: true,
        colorName: "Deep Ocean",
        colorHex: "#0047AB",
        productId: "p2",
        createdAt: new Date(),
        updatedAt: new Date(),
        images: ["https://picsum.photos/seed/vasew/600/600"],
        sizeName: "XXS",
        widthCm: 0,
        heightCm: 0,
        depthCm: 0,
      },
      {
        id: "v4",
        sku: "MUG-GRY",
        price: 22.0,
        currency: CurrencyCode.GBP,
        stock: 30,
        availableForSale: true,
        colorName: "Stone Grey",
        colorHex: "#708090",
        productId: "p2",
        createdAt: new Date(),
        updatedAt: new Date(),
        images: ["https://picsum.photos/seed/vasew/600/600"],
        sizeName: "XXS",
        widthCm: 0,
        heightCm: 0,
        depthCm: 0,
      },
    ],
  },

  // --- Product 3: Multiple Variants (Sizes) ---
  {
    id: "p3",
    name: "Nesting Serving Bowls",
    description: "Elegant bowls that fit perfectly inside each other.",
    slug: "nesting-serving-bowls",
    images: ["https://picsum.photos/seed/bowl1/600/600"],
    categories: ["Dining", "Ceramics"],
    requiresShipping: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    variants: [
      {
        id: "v5",
        sku: "BOWL-L",
        price: 55.0,
        currency: CurrencyCode.GBP,
        stock: 10,
        availableForSale: true,
        sizeName: SizeNames.L,
        widthCm: 30,
        depthCm: 30,
        productId: "p3",
        createdAt: new Date(),
        updatedAt: new Date(),
        images: ["https://picsum.photos/seed/vasew/600/600"],
        heightCm: 0,
      },
      {
        id: "v6",
        sku: "BOWL-XL",
        price: 75.0,
        currency: CurrencyCode.GBP,
        stock: 5,
        availableForSale: true,
        sizeName: SizeNames.XL,
        widthCm: 40,
        depthCm: 40,
        productId: "p3",
        createdAt: new Date(),
        updatedAt: new Date(),
        images: ["https://picsum.photos/seed/vasew/600/600"],
        heightCm: 0,
      },
    ],
  },

  // --- Product 4: Single Variant ---
  {
    id: "p4",
    name: "Clay Incense Holder",
    description: "Simple and functional clay holder for incense sticks.",
    slug: "clay-incense-holder",
    images: ["https://picsum.photos/seed/incense/600/600"],
    categories: ["Home Decor"],
    requiresShipping: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    variants: [
      {
        id: "v7",
        sku: "HOLD-CLAY",
        price: 18.0,
        currency: CurrencyCode.GBP,
        stock: 100,
        availableForSale: true,
        productId: "p4",
        createdAt: new Date(),
        updatedAt: new Date(),
        images: ["https://picsum.photos/seed/vasew/600/600"],
        sizeName: "XXS",
        widthCm: 0,
        heightCm: 0,
        depthCm: 0,
      },
    ],
  },

  // --- Product 5: Single Variant ---
  {
    id: "p5",
    name: "Handmade Soap Dish",
    description: "Textured surface to keep your soap dry.",
    slug: "handmade-soap-dish",
    images: ["https://picsum.photos/seed/soap/600/600"],
    categories: ["Bathroom"],
    requiresShipping: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    variants: [
      {
        id: "v8",
        sku: "SOAP-DISH-01",
        price: 14.0,
        currency: CurrencyCode.GBP,
        stock: 45,
        availableForSale: true,
        productId: "p5",
        createdAt: new Date(),
        updatedAt: new Date(),
        images: ["https://picsum.photos/seed/vasew/600/600"],
        sizeName: "XXS",
        widthCm: 0,
        heightCm: 0,
        depthCm: 0,
      },
    ],
  },

  // --- Product 6: Single Variant ---
  {
    id: "p6",
    name: "Terracotta Plant Pot",
    description: "Breathable terracotta for healthy plant roots.",
    slug: "terracotta-plant-pot",
    images: ["https://picsum.photos/seed/pot/600/600"],
    categories: ["Garden"],
    requiresShipping: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    variants: [
      {
        id: "v9",
        sku: "POT-TERRA",
        price: 28.0,
        currency: CurrencyCode.GBP,
        stock: 20,
        availableForSale: true,
        sizeName: SizeNames.M,
        productId: "p6",
        createdAt: new Date(),
        updatedAt: new Date(),
        images: ["https://picsum.photos/seed/vasew/600/600"],
        widthCm: 0,
        heightCm: 0,
        depthCm: 0,
      },
    ],
  },
];

export const customers: Customer[] = [
  // CUSTOMER 1: Frequent Buyer (Active Cart + Many Orders)
  {
    id: "cust_1",
    firstName: "Luis",
    lastName: "Gaga",
    email: "l.gameiro@gmail.com",
    acceptsMarketing: true,
    createdAt: new Date("2024-10-01"),
    updatedAt: new Date(),
    addresses: [
      {
        id: "addr_1",
        type: "shipping",
        firstName: "Luis",
        lastName: "Gaga",
        company: "Creative Studio",
        streetNumber: "123",
        apartments: "Flat 4B",
        postalCode: "1000-001",
        city: "Lisbon",
        country: "Portugal",
        customerId: "cust_1",
        createdAt: new Date(),
      },
    ],
    cart: {
      id: "cart_1",
      customerId: "cust_1",
      taxesIncluded: true,
      lineItems: [
        {
          variantId: "v1",
          sku: "VASE-S-WHT",
          name: "Minimalist Vase",
          image: "https://picsum.photos/seed/v1/200",
          quantity: 1,
          price: 35.0,
          currency: "EUR",
          sizeName: "S",
          colorName: "White",
        },
      ],
      discounts: [],
      subtotalPrice: 35.0,
      lineItemsSubtotalPrice: 35.0,
      totalPrice: 35.0,
      currency: "EUR",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    orders: Array.from({ length: 8 }).map((_, i) => ({
      id: `ord_1_${i}`,
      customerId: "cust_1",
      status: i === 0 ? OrderStatus.PENDING : OrderStatus.COMPLETED,
      taxesIncluded: true,
      lineItems: [
        {
          variantId: "v3",
          sku: "MUG-BLU",
          name: "Artisan Mug",
          image: "https://picsum.photos/seed/v3/200",
          quantity: 2,
          price: 22.0,
          currency: "EUR",
        },
      ],
      discounts: [],
      subtotalPrice: 44.0,
      lineItemsSubtotalPrice: 44.0,
      totalPrice: 44.0,
      currency: "EUR",
      createdAt: new Date(2024, 10, i + 1),
      updatedAt: new Date(),
    })),
  },

  // CUSTOMER 2: New User (Empty Cart + 2 Orders)
  {
    id: "cust_2",
    firstName: "Ana",
    lastName: "Silva",
    email: "ana.silva@example.pt",
    acceptsMarketing: false,
    createdAt: new Date("2024-11-15"),
    updatedAt: new Date(),
    addresses: [],
    cart: {
      id: "cart_2",
      customerId: "cust_2",
      taxesIncluded: true,
      lineItems: [],
      discounts: [],
      subtotalPrice: 0,
      lineItemsSubtotalPrice: 0,
      totalPrice: 0,
      currency: "EUR",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    orders: [
      {
        id: "ord_2_1",
        customerId: "cust_2",
        status: OrderStatus.PAID,
        taxesIncluded: true,
        lineItems: [
          {
            variantId: "v5",
            sku: "BOWL-L",
            name: "Serving Bowl",
            image: "https://picsum.photos/seed/v5/200",
            quantity: 1,
            price: 55.0,
            currency: "EUR",
          },
        ],
        discounts: [
          {
            code: "WELCOME10",
            type: "PERCENTAGE",
            value: 10,
            amountSaved: 5.5,
          },
        ],
        subtotalPrice: 49.5,
        lineItemsSubtotalPrice: 55.0,
        totalPrice: 49.5,
        currency: "EUR",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "ord_2_2",
        customerId: "cust_2",
        status: OrderStatus.CANCELLED,
        taxesIncluded: true,
        lineItems: [
          {
            variantId: "v1",
            sku: "VASE-S-WHT",
            name: "Vase",
            image: "https://picsum.photos/seed/v1/200",
            quantity: 1,
            price: 35.0,
            currency: "EUR",
          },
        ],
        discounts: [],
        subtotalPrice: 35.0,
        lineItemsSubtotalPrice: 35.0,
        totalPrice: 35.0,
        currency: "EUR",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },

  // CUSTOMER 3: Commercial Client (6 Bulk Orders)
  {
    id: "cust_3",
    firstName: "John",
    lastName: "Doe",
    company: "Hotel Grande",
    email: "john@hotelgrande.com",
    acceptsMarketing: true,
    createdAt: new Date("2024-09-01"),
    updatedAt: new Date(),
    addresses: [],
    cart: {
      id: "cart_3",
      customerId: "cust_3",
      taxesIncluded: true,
      lineItems: [],
      discounts: [],
      subtotalPrice: 0,
      lineItemsSubtotalPrice: 0,
      totalPrice: 0,
      currency: "EUR",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    orders: Array.from({ length: 6 }).map((_, i) => ({
      id: `ord_3_${i}`,
      customerId: "cust_3",
      status: OrderStatus.SHIPPED,
      taxesIncluded: true,
      lineItems: [
        {
          variantId: "v3",
          sku: "MUG-BLU",
          name: "Bulk Mugs",
          image: "https://picsum.photos/seed/v3/200",
          quantity: 20,
          price: 20.0,
          currency: "EUR",
        },
      ],
      discounts: [],
      subtotalPrice: 400.0,
      lineItemsSubtotalPrice: 400.0,
      totalPrice: 400.0,
      currency: "EUR",
      createdAt: new Date(2024, 8, i + 10),
      updatedAt: new Date(),
    })),
  },

  // CUSTOMER 4: The Window Shopper (Active Cart + 4 Pending/Mixed Orders)
  {
    id: "cust_4",
    firstName: "Maria",
    lastName: "Rossi",
    email: "m.rossi@italy.it",
    acceptsMarketing: true,
    createdAt: new Date("2024-12-01"),
    updatedAt: new Date(),
    addresses: [],
    cart: {
      id: "cart_4",
      customerId: "cust_4",
      taxesIncluded: true,
      lineItems: [
        {
          variantId: "v8",
          sku: "SOAP-DISH",
          name: "Soap Dish",
          image: "https://picsum.photos/seed/v8/200",
          quantity: 2,
          price: 14.0,
          currency: "EUR",
        },
      ],
      discounts: [],
      subtotalPrice: 28.0,
      lineItemsSubtotalPrice: 28.0,
      totalPrice: 28.0,
      currency: "EUR",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    orders: Array.from({ length: 4 }).map((_, i) => ({
      id: `ord_4_${i}`,
      customerId: "cust_4",
      status: i % 2 === 0 ? OrderStatus.PENDING : OrderStatus.PAID,
      taxesIncluded: true,
      lineItems: [
        {
          variantId: "v9",
          sku: "POT-TERRA",
          name: "Plant Pot",
          image: "https://picsum.photos/seed/v9/200",
          quantity: 1,
          price: 28.0,
          currency: "EUR",
        },
      ],
      discounts: [],
      subtotalPrice: 28.0,
      lineItemsSubtotalPrice: 28.0,
      totalPrice: 28.0,
      currency: "EUR",
      createdAt: new Date(),
      updatedAt: new Date(),
    })),
  },
];
